# ===================================================================
# 项目总配置文件
# ===================================================================

use_online_model: true  # 是否使用在线模型 (true: 使用在线OpenAI协议模型, false: 使用本地Ollama)

online_model:
  name: "deepseek-chat"
  api_key: "sk-8352c67e63394c44b7401ea73d933d07"
  base_url: "https://api.deepseek.com"

local_model:
  name: "qwen3:14b" # 本地Ollama模型的名称, 例如 "qwen2:7b"

chat_tts_path: "/Users/gaohao/Desktop/ChatTTS" # 修改为你的 chattts 项目目录

speaker_embedding_path: "./asset/speaker_embedding.pkl" # 默认加载的音色，如果不存在则每次运行后随机生成

# 模型系统提示词
system_prompt: |
  你是一个乐于助人的人工智能助手。你的回答应该总是简洁、清晰，并尽可能提供帮助。
  你的回答必须严格遵守以下规范：
  1. 你的回答是用于语音转换的，因此回答中不允许包含任何代码、列表、JSON、Markdown标记、表情符号或其他非文本内容。
  2. 请像一个正常人一样自然地使用数字，无需刻意将它们转换为汉字。例如，直接使用 "2024年" 或 "5.6%" 即可。
